version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bodystats
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_DATABASE: bodystats
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bodystats_network

  app:
    image: bodystats:latest
    container_name: bodystats
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/bodystats?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      - mysql
    networks:
      - bodystats_network

volumes:
  mysql_data:

networks:
  gym_network:







