spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_activities?allowPublicKeyRetrieval=true&useSSL=false
    username: Simida
    password: ITea2020Home
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    show-sql: true
